server:
  port: ${CUSTOM.SERVER.PORT:9090}
  
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA.SERVER.HOSTNAME:http://localhost:8761/eureka}
      
spring:
  cloud:
    gateway:
      routes:
        - id: user-services  #este es un identificador no tiene nada que ver con algun id
          uri: user-services #este id debe estar creado en el eureka
          predicates:
            - Path=/api/user-service/**
          filters:
            - StripPrefix=2  #tiene que ver con el path, es una parte de seguridad