server:
  port: ${CUSTOM.SERVER.PORT:9002}
  
eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA.SERVER.HOSTNAME:http://localhost:8761/eureka}
    fetchRegistry: true
    
## conexion a la base de datos
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mitocode
      #username: '{cipher}' #se puede usar de esta manera
      #password: '{cipher}' #se puede usar de esta manera
      uri: mongodb://mitocode:mitocode@localhost:27017
      authentication-database: admin