server:
  port: ${CUSTOM.SERVER.PORT:9004}
  
eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA.SERVER.HOSTNAME:http://localhost:8761/eureka}
    fetchRegistry: true
    healthcheck: # para se chequee el servicio actuator el estado del servicio 
      enable: true
    refresh: # para se chequee el servicio actuator el estado del servicio 
      enable: true    
    
## conexion a la base de datos
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mitocode
      #username: '{cipher}' #se puede usar de esta manera
      #password: '{cipher}' #se puede usar de esta manera
      uri: mongodb://mitocode:mitocode@localhost:27017
      authentication-database: admin
      
# configuracion de actuator 
info:
  app:
    name: Microservicio User Service
    description: Módulo de la arquitectura que disponibiliza información de los Usuarios
    version: 1.0

management:
  auditevents:
    enable: true
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
  endpoint:
    health:
      group:
        custom:
          include: diskSpace, ping, memory, mem
          show-component: always
          show-details: always
  info:
    env:
      enabled: true
  health:
    env:
      enabled: true